spring.application.name=srei
server.port=8080
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/bdsreiwdauxgit1
spring.datasource.username=appuser1
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
jwt.secret=tuClaveSuperLargaYSeguraAquiSinCaracteresRaros1234567890abcdefghi
jwt.expiration=86400000
openrouter.api.key=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

# CONFIGURACIÓN PARA SUBIDA DE ARCHIVOS
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=40MB